services:

  libreddit:
    container_name: libreddit
    image: docker.io/spikecodes/libreddit:latest
    restart: always
    ports:
      - "8083:8080"
    environment:
      - "LIBREDDIT_DEFAULT_THEME=dark"
      - "LIBREDDIT_DEFAULT_LAYOUT=card"
      - "LIBREDDIT_DEFAULT_COMMENT_SORT=top"
      - "LIBREDDIT_DEFAULT_POST_SORT=top"
      - "LIBREDDIT_DEFAULT_SHOW_NSFW=off"
      - "LIBREDDIT_DEFAULT_USE_HLS=on"
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost:8080/settings"]
      interval: 5m
      timeout: 3s
