services:
  rimgo:
    container_name: rimgo
    image: quay.io/pussthecatorg/rimgo:latest
    restart: always
    ports:
      - "8085:3000"
    environment:
      - "PORT=3000"
      - "ADDRESS=0.0.0.0"
      - "IMGUR_CLIENT_ID=546c25a59c58ad7"

